# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

includes:
  common:
    taskfile: ./Taskfile.common.yml
    dir: .
    optional: false

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
